name: Generate Go Sum

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Create go.mod file
      run: |
        echo "module temp-go-project" > go.mod
        echo "go 1.16" >> go.mod
        echo "require (" >> go.mod
        echo "    github.com/tritu/utls v1.6.7" >> go.mod
        echo ")" >> go.mod

    - name: Run go mod tidy
      run: go mod tidy

    - name: Display go.sum
      run: cat go.sum
